/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AgentBankLendingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE_BPS"
      | "LOAN_DURATION"
      | "TIER1_MAX"
      | "TIER1_SCORE"
      | "TIER2_MAX"
      | "TIER2_SCORE"
      | "TIER3_MAX"
      | "TIER3_SCORE"
      | "USDT_DECIMALS"
      | "agentScore"
      | "borrowerLoans"
      | "claimFeeTokens"
      | "fundPool"
      | "getBorrowerLoans"
      | "getMaxLoan"
      | "liquidate"
      | "loans"
      | "owner"
      | "poolBalance"
      | "renounceOwnership"
      | "repayLoan"
      | "requestLoan"
      | "totalLoans"
      | "transferOwnership"
      | "usdt"
      | "withdrawPool"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeeTokensClaimed"
      | "LoanDefaulted"
      | "LoanRepaid"
      | "LoanRequested"
      | "OwnershipTransferred"
      | "PoolFunded"
      | "PoolWithdrawn"
  ): EventFragment;

  encodeFunctionData(functionFragment: "FEE_BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "LOAN_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TIER1_MAX", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "TIER1_SCORE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TIER2_MAX", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "TIER2_SCORE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TIER3_MAX", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "TIER3_SCORE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USDT_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentScore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "borrowerLoans",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimFeeTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBorrowerLoans",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMaxLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "loans", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "repayLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalLoans",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawPool",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "FEE_BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "LOAN_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TIER1_MAX", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "TIER1_SCORE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TIER2_MAX", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "TIER2_SCORE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TIER3_MAX", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "TIER3_SCORE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USDT_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agentScore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "borrowerLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimFeeTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBorrowerLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMaxLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repayLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalLoans", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPool",
    data: BytesLike
  ): Result;
}

export namespace FeeTokensClaimedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [loanId: bigint, borrower: string, amount: bigint];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanDefaultedEvent {
  export type InputTuple = [loanId: BigNumberish, borrower: AddressLike];
  export type OutputTuple = [loanId: bigint, borrower: string];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRepaidEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    totalPaid: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrower: string,
    totalPaid: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    totalPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRequestedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish,
    dueDate: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrower: string,
    amount: bigint,
    fee: bigint,
    dueDate: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    amount: bigint;
    fee: bigint;
    dueDate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolFundedEvent {
  export type InputTuple = [funder: AddressLike, amount: BigNumberish];
  export type OutputTuple = [funder: string, amount: bigint];
  export interface OutputObject {
    funder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolWithdrawnEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentBankLending extends BaseContract {
  connect(runner?: ContractRunner | null): AgentBankLending;
  waitForDeployment(): Promise<this>;

  interface: AgentBankLendingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  LOAN_DURATION: TypedContractMethod<[], [bigint], "view">;

  TIER1_MAX: TypedContractMethod<[], [bigint], "view">;

  TIER1_SCORE: TypedContractMethod<[], [bigint], "view">;

  TIER2_MAX: TypedContractMethod<[], [bigint], "view">;

  TIER2_SCORE: TypedContractMethod<[], [bigint], "view">;

  TIER3_MAX: TypedContractMethod<[], [bigint], "view">;

  TIER3_SCORE: TypedContractMethod<[], [bigint], "view">;

  USDT_DECIMALS: TypedContractMethod<[], [bigint], "view">;

  agentScore: TypedContractMethod<[], [string], "view">;

  borrowerLoans: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  claimFeeTokens: TypedContractMethod<
    [loanId: BigNumberish],
    [void],
    "nonpayable"
  >;

  fundPool: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getBorrowerLoans: TypedContractMethod<
    [borrower: AddressLike],
    [bigint[]],
    "view"
  >;

  getMaxLoan: TypedContractMethod<[score: BigNumberish], [bigint], "view">;

  liquidate: TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;

  loans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean, boolean, boolean] & {
        borrower: string;
        amount: bigint;
        fee: bigint;
        dueDate: bigint;
        repaid: boolean;
        defaulted: boolean;
        feeClaimed: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  poolBalance: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  repayLoan: TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;

  requestLoan: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  totalLoans: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdt: TypedContractMethod<[], [string], "view">;

  withdrawPool: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOAN_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER1_MAX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER1_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER2_MAX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER2_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER3_MAX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER3_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDT_DECIMALS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentScore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "borrowerLoans"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimFeeTokens"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fundPool"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBorrowerLoans"
  ): TypedContractMethod<[borrower: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getMaxLoan"
  ): TypedContractMethod<[score: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "liquidate"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "loans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean, boolean, boolean] & {
        borrower: string;
        amount: bigint;
        fee: bigint;
        dueDate: bigint;
        repaid: boolean;
        defaulted: boolean;
        feeClaimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "poolBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "repayLoan"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestLoan"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "totalLoans"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdt"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawPool"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "FeeTokensClaimed"
  ): TypedContractEvent<
    FeeTokensClaimedEvent.InputTuple,
    FeeTokensClaimedEvent.OutputTuple,
    FeeTokensClaimedEvent.OutputObject
  >;
  getEvent(
    key: "LoanDefaulted"
  ): TypedContractEvent<
    LoanDefaultedEvent.InputTuple,
    LoanDefaultedEvent.OutputTuple,
    LoanDefaultedEvent.OutputObject
  >;
  getEvent(
    key: "LoanRepaid"
  ): TypedContractEvent<
    LoanRepaidEvent.InputTuple,
    LoanRepaidEvent.OutputTuple,
    LoanRepaidEvent.OutputObject
  >;
  getEvent(
    key: "LoanRequested"
  ): TypedContractEvent<
    LoanRequestedEvent.InputTuple,
    LoanRequestedEvent.OutputTuple,
    LoanRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PoolFunded"
  ): TypedContractEvent<
    PoolFundedEvent.InputTuple,
    PoolFundedEvent.OutputTuple,
    PoolFundedEvent.OutputObject
  >;
  getEvent(
    key: "PoolWithdrawn"
  ): TypedContractEvent<
    PoolWithdrawnEvent.InputTuple,
    PoolWithdrawnEvent.OutputTuple,
    PoolWithdrawnEvent.OutputObject
  >;

  filters: {
    "FeeTokensClaimed(uint256,address,uint256)": TypedContractEvent<
      FeeTokensClaimedEvent.InputTuple,
      FeeTokensClaimedEvent.OutputTuple,
      FeeTokensClaimedEvent.OutputObject
    >;
    FeeTokensClaimed: TypedContractEvent<
      FeeTokensClaimedEvent.InputTuple,
      FeeTokensClaimedEvent.OutputTuple,
      FeeTokensClaimedEvent.OutputObject
    >;

    "LoanDefaulted(uint256,address)": TypedContractEvent<
      LoanDefaultedEvent.InputTuple,
      LoanDefaultedEvent.OutputTuple,
      LoanDefaultedEvent.OutputObject
    >;
    LoanDefaulted: TypedContractEvent<
      LoanDefaultedEvent.InputTuple,
      LoanDefaultedEvent.OutputTuple,
      LoanDefaultedEvent.OutputObject
    >;

    "LoanRepaid(uint256,address,uint256)": TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;
    LoanRepaid: TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;

    "LoanRequested(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      LoanRequestedEvent.InputTuple,
      LoanRequestedEvent.OutputTuple,
      LoanRequestedEvent.OutputObject
    >;
    LoanRequested: TypedContractEvent<
      LoanRequestedEvent.InputTuple,
      LoanRequestedEvent.OutputTuple,
      LoanRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PoolFunded(address,uint256)": TypedContractEvent<
      PoolFundedEvent.InputTuple,
      PoolFundedEvent.OutputTuple,
      PoolFundedEvent.OutputObject
    >;
    PoolFunded: TypedContractEvent<
      PoolFundedEvent.InputTuple,
      PoolFundedEvent.OutputTuple,
      PoolFundedEvent.OutputObject
    >;

    "PoolWithdrawn(address,uint256)": TypedContractEvent<
      PoolWithdrawnEvent.InputTuple,
      PoolWithdrawnEvent.OutputTuple,
      PoolWithdrawnEvent.OutputObject
    >;
    PoolWithdrawn: TypedContractEvent<
      PoolWithdrawnEvent.InputTuple,
      PoolWithdrawnEvent.OutputTuple,
      PoolWithdrawnEvent.OutputObject
    >;
  };
}
