/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as test from "./test";
export { AgentBankLending__factory } from "./AgentBankLending__factory";
export { AgentScore__factory } from "./AgentScore__factory";
